import type {
	ContributionLinkKind,
	ContributionLinkOptions,
	ContributionType,
	RepoType,
} from "./types.ts";

import {
	type ContributionTypeName,
	contributionTypes,
} from "./contributionTypes.ts";

const defaultHosts: Record<RepoType, string> = {
	github: "https://github.com",
	gitlab: "https://gitlab.com",
};

// These intentionally match the links generated by all-contributors-cli:
// https://github.com/all-contributors/cli/blob/main/src/repo/index.js
const linkPaths: Record<
	RepoType,
	Record<ContributionLinkKind, (login: string) => string>
> = {
	github: {
		commits: (login) => `commits?author=${login}`,
		issues: (login) => `issues?q=author%3A${login}`,
		reviews: (login) => `pulls?q=is%3Apr+reviewed-by%3A${login}`,
	},
	gitlab: {
		commits: () => `commits/master`,
		issues: (login) => `issues?author_username=${login}`,
		reviews: (login) =>
			`merge_requests?scope=all&state=all&approver_usernames[]=${login}`,
	},
};

/**
 * Creates the URL that a contributor's contribution links to in a README table.
 * Contribution types without a repository page link to a `#type-login` anchor.
 */
export function createContributionLink(
	contribution: ContributionTypeName,
	options: ContributionLinkOptions,
) {
	const { login, projectName, projectOwner, repoType = "github" } = options;
	const type: ContributionType = contributionTypes[contribution];

	if (!type.link || !login) {
		return login ? `#${contribution}-${login}` : `#${contribution}`;
	}

	const repoHost = options.repoHost ?? defaultHosts[repoType];

	return `${repoHost}/${projectOwner}/${projectName}/${linkPaths[repoType][type.link](login)}`;
}
